# @package _global_

defaults:
  - override /hydra/launcher: ray

hydra:
  launcher:
    ray: 
      remote:
        num_gpus: 0.5
        runtime_env:
          env_vars:
              WANDB_API_KEY: ${oc.env:WANDB_API_KEY}
