# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm
  - override /trainer: gpu

hydra:
  launcher:
    account: rrg-bengioy-ad
    cpus_per_task: 4
    mem_gb: 48
    gres: gpu:1
    timeout_min: 3880
    #exclude: cn-g[005-012,014,017-026] # exclude mig for ddp
    array_parallelism: 10 # max num of tasks to run in parallel (via job array)
    setup:
      - "module purge"
      - "module load python/3.10 scipy-stack"
      - "virtualenv --no-download $SLURM_TMPDIR/env"
      - "source $SLURM_TMPDIR/env/bin/activate"
      - "pip install --no-index --upgrade pip"
      - "pip install --no-index -r /home/atong01/requirements.txt"

logger:
  wandb:
    offline: True
trainer:
  devices: 1
